name: 'cleansacmc'

learning_rate: 0.001
gamma: 0.95
tau: 0.05
use_her: False
ent_coef: auto
n_critics: 1
hidden_size: 256

learning_starts: 1000
batch_size: 2048

# morphological computation hyperparameters
mc:
  learning_rate: 0.001
  reward_eta: 0.2 # small bonus by default
  hidden_size: 256
