name: 'cleanppo'
learning_rate: 3e-4
n_steps: 2048
batch_size: 64 # The batch size for the training
n_epochs: 10 # These are the training epochs for the neural network training, not the rollout epochs (these are in main.yaml)
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
clip_range_vf: null
normalize_advantage: true
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
