# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: cleansac

env: 'parking-limited-v0'

# these parameters were not optimized for this environment!
algorithm:
  use_her: True
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  gamma: 0.95
  tau: 0.02
  n_critics: 2

performance_testing_conditions:
  # In 2 out of 3 tests, the eval/success rate should be at least 0.8 after 36k steps.

  total_runs: 3 # How many runs in total:

  succ_runs: 2 # This number of runs should meet the conditions:

  eval_columns: eval/success_rate # This is what we evaluate to determine success. Will use this to override the \'early_stop_data_column\' parameter of main.yaml

  eval_value: 0.8 # This is the value we determine for success. Will use this to determine and override the \'early_stop_threshold\' parameter of main.yaml

  # ca. 10 minutes with GPU
  max_steps: 36_000 # This is the time limit for checking the success. Will use this and the \'eval_after_n_steps\' parameter of main.yaml to determine the n_epochs parameter in main.yaml.

hydra:
  sweeper:
    n_jobs: 3
    _target_: hydra_plugins.hydra_custom_optuna_sweeper.performance_testing_sweeper.PerformanceTestingSweeper
    study_name: cleansac_her_Parking-test
