# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: sac

n_epochs: 200
eval_after_n_steps: 10000
early_stop_threshold: 0.3
early_stop_data_column: 'eval/success_rate'
render: 'none'

env: 'MetaW-push-v2'

algorithm:
  replay_buffer_class: null
  buffer_size: 1000000
  batch_size: 256
  policy: MlpPolicy
  policy_kwargs:
    net_arch:
      - 256
      - 256
      - 256
hydra:
  sweeper:
    study_name: sac_MetaW-Push
    max_trials: 32
    n_jobs: 10
    direction: maximize
    max_duration_minutes: 18000
    min_trials_per_param: 2
    max_trials_per_param: 3
    search_space:
      ++algorithm.learning_rate:
        type: float
        low: 0.00005
        high: 0.001
        log: true
      ++algorithm.gamma:
        type: float
        low: 0.8
        high: 0.99
        log: true
      ++algorithm.tau:
        type: float
        low: 0.0005
        high: 0.01
        log: true
      ++algorithm.policy_kwargs.n_critics:
        type: int
        low: 2
        high: 2
