# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.

# SB3-SAC HER sparse

defaults:
  - override /algorithm: sac

n_epochs: 200
eval_after_n_steps: 10000
early_stop_threshold: 0.5
render: 'none'

env: 'MetaW-pick-place-v2-sparse'

algorithm:
  replay_buffer_class: HerReplayBuffer
  buffer_size: 1000000
  batch_size: 256
  policy: MultiInputPolicy
  policy_kwargs:
    net_arch:
      - 256
      - 256
      - 256
hydra:
  sweeper:
    study_name: sacher_MetaW-PickPlace-sparse
    max_trials: 32
    n_jobs: 3
    direction: maximize
    max_duration_minutes: 18000
    min_trials_per_param: 3
    max_trials_per_param: 6
    search_space:
      ++algorithm.learning_rate:
        type: float
        low: 0.0001
        high: 0.002
        log: true
      ++algorithm.gamma:
        type: float
        low: 0.9
        high: 0.99
        log: true
      ++algorithm.tau:
        type: float
        low: 0.001
        high: 0.1
        log: true
      ++algorithm.policy_kwargs.n_critics:
        type: int
        low: 2
        high: 2
